ДЗ по третьей неделе
furrrax/loft-taxi pull request #3
Opened 2022-09-09 18:46 UTC by furrrax

Реализовано:
- Сверстаны все страницы и формы
- Подключен react-router-dom
- Навигация переписана на react-router-dom
- Подключен Redux
- Авторизация переписана на Redux
- Реализован middleware для общения с сервером
- Статус авторизации кэшируется в localstorage

Принцип работы приложения:

Форма регистрации:
После ввода данных происходит автологин и редирект на внутреннюю страницу с картой, в localstorage записывается ключ autorize со статусом true.
После нажатия на Выход происходит редирект на главную с формой входа, в localstorage записывается ключ autorize со статусом false.

Форма входа:
После ввода валидных данных происходит редирект на внутреннюю страницу с картой, в localstorage записывается ключ autorize со статусом true.
После нажатия на Выход происходит редирект на главную с формой входа, в localstorage записывается ключ autorize со статусом false.

Localstorage:
Если записан ключ со статусом true, то происходит внутренняя проверка и статус в store isLoggedIn меняется на true,  юзеру открыт доступ на все страницы, в т.ч. и при первой загрузке приложения. По-умолчанию редиректит на внутреннюю страницу с картой.

2022-09-10 20:59 UTC, nlold commented on src/index.css
> +ul, p, h1, h2, h3, h4, h5, h6 {
Лучше уже сейчас разбить этот большой css на несколько. И хранить этот css по компонентам, например.

2022-09-10 21:01 UTC, nlold commented on src/App.js
> +/* import { Provider } from 'react-redux';
Не забывай удалять лишние комменты

2022-09-10 21:04 UTC, nlold commented on src/redux/actions/user.js
> +export const AUTHENTICATE = 'AUTHENTICATE';
Лучше соблюдать единый стиль написания. Либо через createAction, либо старым способом, как AUTHENTICATE и REGISTER. Я бы рекомендовать уже все переписать на createAction, но выбор за тобой.

2022-09-10 21:04 UTC, nlold commented on src/redux/reducers/user.js
> +            console.log('LogIn action success')
Логи тоже не забывай подчищать

2022-09-10 21:06 UTC, nlold commented on src/pages/PageMain.jsx
> +            {loggedIn ? (
Вот такое конструкции лучше выносить до return в конструкцию if. То есть if (loggedIn) {return <Navigate to="/map" />}

2022-09-10 21:07 UTC, nlold commented on src/pages/PageMap.jsx
> +    const LogOff = () => {
Не забывай оборачивать функции в useCallback и именовать функции с маленькой буквы

2022-09-10 21:07 UTC, nlold commented on src/pages/PageMap.jsx
> +            {loggedIn ? (
Аналогично про loggedIn

2022-09-10 21:07 UTC, nlold commented on src/pages/PageProfile.jsx
>      const logOff = () => {
Аналогично про useCallback

2022-09-10 21:08 UTC, nlold commented on src/pages/PageProfile.jsx
> +            {loggedIn ? (
Аналогично про вынесение в if

2022-09-10 21:08 UTC, nlold commented on src/components/FormReg.jsx
> +function FormReg() {
Не забывай про отступы

2022-09-10 21:09 UTC, nlold commented on src/components/FormReg.jsx
> +    const emailHandleChange = (event) => {
Аналогично про useCallback тут и в следующих функциях

2022-09-10 21:09 UTC, nlold commented on src/components/FormReg.jsx
> +            {loggedIn ? (
аналогично про вынесение в if

2022-09-10 21:09 UTC, nlold commented on src/components/FormLogin.jsx
> +    const emailHandleChange = (event) => {
Аналогично про useCallback тут и дальше

2022-09-10 21:09 UTC, nlold commented on src/components/FormLogin.jsx
> +            {loggedIn ? (
Аналогично про loggedIn

2022-09-10 21:11 UTC, nlold commented on src/components/popup/PopupOrder.jsx
> +        <form className="popup popup__order popup--map">
Очень круто, что сам сверстал все эти попапы, но не забывай про то, что ты можешь использовать многие компоненты из MaterialUI, которые уже готовы =) Это ускорит твою работу над проектом и позволит сконцентрироваться больше на логике.

2022-09-10 21:12 UTC, nlold requested changes
В целом, все окей. В основном не очень значительные правки.

2022-09-11 06:35 UTC, furrrax commented on src/redux/reducers/user.js
> +            console.log('LogIn action success')
Исправлено

2022-09-11 06:50 UTC, furrrax commented on src/pages/PageMap.jsx
> +    const LogOff = () => {
Исправлено

2022-09-11 06:50 UTC, furrrax commented on src/pages/PageProfile.jsx
>      const logOff = () => {
Исправлено

2022-09-11 06:51 UTC, furrrax commented on src/App.js
> +/* import { Provider } from 'react-redux';
Исправлено

2022-09-11 07:19 UTC, furrrax commented on src/pages/PageMain.jsx
> +            {loggedIn ? (
Исправлено

2022-09-11 07:19 UTC, furrrax commented on src/pages/PageMap.jsx
> +            {loggedIn ? (
Исправлено

2022-09-11 07:19 UTC, furrrax commented on src/pages/PageProfile.jsx
> +            {loggedIn ? (
Исправлено

2022-09-11 07:21 UTC, furrrax commented on src/components/FormReg.jsx
> +function FormReg() {
Исправлено

2022-09-11 07:21 UTC, furrrax commented on src/components/FormReg.jsx
> +    const emailHandleChange = (event) => {
Исправлено

2022-09-11 07:21 UTC, furrrax commented on src/components/FormReg.jsx
> +            {loggedIn ? (
Исправлено

2022-09-11 07:22 UTC, furrrax commented on src/components/FormLogin.jsx
> +    const emailHandleChange = (event) => {
Исправлено

2022-09-11 07:22 UTC, furrrax commented on src/components/FormLogin.jsx
> +            {loggedIn ? (
Исправлено

2022-09-11 08:20 UTC, furrrax commented on src/redux/actions/user.js
> +export const AUTHENTICATE = 'AUTHENTICATE';
Исправлено

2022-09-11 08:43 UTC, nlold commented on src/components/FormLogin.jsx
> +    } else {
В целом ОК, но else можно опускать вовсе и сразу писать return ...

2022-09-11 08:43 UTC, nlold commented on src/components/FormReg.jsx
> +    } else {
Аналогично про else

2022-09-11 08:44 UTC, nlold commented on src/pages/PageMain.jsx
> +    } else {
Аналогично

2022-09-11 08:45 UTC, nlold commented on src/pages/PageMap.jsx
> +            <Navigate to="/login" />
Особые случаи всегда лучше выносить перед основным return. Лучше использовать такую логику: обработали особую логику -> логика для всех остальных случаев

2022-09-11 08:45 UTC, nlold commented on src/pages/PageProfile.jsx
> +    } else {
Аналогично

2022-09-11 08:48 UTC, nlold approved these changes
Все гуд, апрув. Только пару стилистических замечаний поправь и вливай в основную ветку

2022-09-11 09:03 UTC, furrrax commented on src/components/FormLogin.jsx
> +    } else {
Исправлено

2022-09-11 09:03 UTC, furrrax commented on src/components/FormReg.jsx
> +    } else {
Исправлено

2022-09-11 09:03 UTC, furrrax commented on src/pages/PageMain.jsx
> +    } else {
Исправлено

2022-09-11 09:03 UTC, furrrax commented on src/pages/PageMap.jsx
> +            <Navigate to="/login" />
Исправлено

2022-09-11 09:04 UTC, furrrax commented on src/pages/PageProfile.jsx
> +    } else {
Исправлено

2022-09-11 09:05 UTC, merged